### ISSUE TITLE
Bash syntax highlighting is broken for repeated expressions and multi-line comments

### ISSUE THREAD

**Issue by whalehub** [w4/bin#17] opened 2020-07-24 15:33 UTC
**Environment:**
- **OS:** Debian 10
- **Bin:** 2bbab69 (built from source)

**Expected syntax highlighting:**
- All comments are greyed out.
- All `if` expressions are highlighted.

```bash
#!/bin/bash

# This is a comment
# This is also a comment

# This is a comment
# This is also a comment

if [ "a" = "b" ]; then true; fi
if [ "b" = "c" ]; then false; fi

if [ "a" = "b" ]; then true; fi
if [ "b" = "c" ]; then false; fi

# This is a comment
# This is also a comment

# This is a comment
# This is also a comment

if [ "a" = "b" ]; then true; fi
if [ "b" = "c" ]; then false; fi

if [ "a" = "b" ]; then true; fi
if [ "b" = "c" ]; then false; fi

# This is a comment
# This is also a comment

# This is a comment
# This is also a comment
```

**Actual syntax highlighting:**
- Only the first comment is greyed out. This "limit" only resets when two comment lines are separated by an expression. A blank line does not reset the limit.
- Only the first `if` expression is highlighted. This "limit" only resets when two lines with `if` expressions are separated by a blank line **and** a comment line. A blank line or comment line by itself does not reset the limit.

**Comment by w4** [comment] 2020-08-02 13:37
Thanks for the issue. We actually use a library called [syntect](https://github.com/trishume/syntect) for syntax highlighting which is the same library that backs [bat](https://github.com/sharkdp/bat). Obviously the highlighting works fine in bat so I'm inclined to say this is caused by the sublime theme we're using, which is currently `base16-ocean.dark` as defined in `src/highlighter.rs`.

Perhaps this could be fixed with a version bump to syntect if they keep on top of theme updates. Or, if you're comfortable recompiling bin from source, feel free to change the Sublime Text theme to another one in syntect or we could start bundling our own. Perhaps this is better suited as a configuration value.

**Comment by whalehub** [comment] 2020-08-07 15:25
@w4 I compiled `bin` from source twice with alternate themes just now (`base16-eighties.dark` and `Solarized (dark)`), but the only thing that changed are the colors of the syntax highlighting (see screenshot). The parsing issue described in this issue remained consistent across themes.

![solarized](https://xbb.datahoarder.dev/VUSu3/jiPejagE98.png/raw)

**Comment by w4** [comment] 2020-08-07 16:25
Hey, thanks for looking into this a bit for me. This seems to be a problem with syntact's `highlighted_html_for_string`, using a `ClassedHTMLGenerator` seems to work a bit better, though it's still not perfect (the `fi` is highlighted the same as the command) - and it adds quite a bit of weight to the page since we're bundling a sublime theme with it.

You can use [this patch](https://gist.github.com/w4/b2960e19784a42e2bebc3aa40e464b16) to fix the comments issue for now, but might be worth raising an issue with syntact.

Cheers

**Comment by whalehub** [comment] 2020-08-07 16:51
@w4 Thanks for the patch! This is a pretty big improvement.

It's true that this increases the page size by about 10KB, but thanks to the gzip/brotli compression applied by Nginx, the amount of data that actually needs to be transferred over the wire only increases by a mere 1KB.

**Compiled without patch**
![unpatched](https://xbb.datahoarder.dev/VUSu3/piRUWEza02.png/raw)

**Compiled with patch**
![patched](https://xbb.datahoarder.dev/VUSu3/TokAvAsO00.png/raw)

![patch](https://xbb.datahoarder.dev/VUSu3/xaKuMena25.png/raw)

**Closed** 2021-04-03 05:34 UTC
